const countryCodeMap = {
  "Finland": "fi",
  "Denmark": "dk",
  "Norway": "no",
  "Iceland": "is",
  "Netherlands": "nl",
  "Switzerland": "ch",
  "Sweden": "se",
  "New Zealand": "nz",
  "Canada": "ca",
  "Austria": "at",
  "Australia": "au",
  "Costa Rica": "cr",
  "Israel": "il",
  "Luxembourg": "lu",
  "United Kingdom": "gb",
  "Ireland": "ie",
  "Germany": "de",
  "Belgium": "be",
  "United States": "us",
  "Czech Republic": "cz",
  "United Arab Emirates": "ae",
  "Malta": "mt",
  "Mexico": "mx",
  "France": "fr",
  "Taiwan": "tw",
  "Chile": "cl",
  "Guatemala": "gt",
  "Saudi Arabia": "sa",
  "Qatar": "qa",
  "Spain": "es",
  "Panama": "pa",
  "Brazil": "br",
  "Uruguay": "uy",
  "Singapore": "sg",
  "El Salvador": "sv",
  "Italy": "it",
  "Bahrain": "bh",
  "Slovakia": "sk",
  "Trinidad & Tobago": "tt",
  "Poland": "pl",
  "Uzbekistan": "uz",
  "Lithuania": "lt",
  "Colombia": "co",
  "Slovenia": "si",
  "Nicaragua": "ni",
  "Kosovo": "xk",
  "Argentina": "ar",
  "Romania": "ro",
  "Cyprus": "cy",
  "Ecuador": "ec",
  "Kuwait": "kw",
  "Thailand": "th",
  "Latvia": "lv",
  "South Korea": "kr",
  "Estonia": "ee",
  "Jamaica": "jm",
  "Mauritius": "mu",
  "Japan": "jp",
  "Honduras": "hn",
  "Kazakhstan": "kz",
  "Bolivia": "bo",
  "Hungary": "hu",
  "Paraguay": "py",
  "Northern Cyprus": "cy",
  "Peru": "pe",
  "Portugal": "pt",
  "Pakistan": "pk",
  "Russia": "ru",
  "Philippines": "ph",
  "Serbia": "rs",
  "Moldova": "md",
  "Libya": "ly",
  "Montenegro": "me",
  "Tajikistan": "tj",
  "Croatia": "hr",
  "Hong Kong": "hk",
  "Dominican Republic": "do",
  "Bosnia and Herzegovina": "ba",
  "Turkey": "tr",
  "Malaysia": "my",
  "Belarus": "by",
  "Greece": "gr",
  "Mongolia": "mn",
  "North Macedonia": "mk",
  "Nigeria": "ng",
  "Kyrgyzstan": "kg",
  "Turkmenistan": "tm",
  "Algeria": "dz",
  "Morocco": "ma",
  "Azerbaijan": "az",
  "Lebanon": "lb",
  "Indonesia": "id",
  "China": "cn",
  "Vietnam": "vn",
  "Bhutan": "bt",
  "Cameroon": "cm",
  "Bulgaria": "bg",
  "Ghana": "gh",
  "Ivory Coast": "ci",
  "Nepal": "np",
  "Jordan": "jo",
  "Benin": "bj",
  "Congo (Brazzaville)": "cg",
  "Gabon": "ga",
  "Laos": "la",
  "South Africa": "za",
  "Albania": "al",
  "Venezuela": "ve",
  "Cambodia": "kh",
  "Palestinian Territories": "ps",
  "Senegal": "sn",
  "Somalia": "so",
  "Namibia": "na",
  "Niger": "ne",
  "Burkina Faso": "bf",
  "Armenia": "am",
  "Iran": "ir",
  "Guinea": "gn",
  "Georgia": "ge",
  "Gambia": "gm",
  "Kenya": "ke",
  "Mauritania": "mr",
  "Mozambique": "mz",
  "Tunisia": "tn",
  "Bangladesh": "bd",
  "Iraq": "iq",
  "Congo (Kinshasa)": "cd",
  "Mali": "ml",
  "Sierra Leone": "sl",
  "Sri Lanka": "lk",
  "Myanmar": "mm",
  "Chad": "td",
  "Ukraine": "ua",
  "Ethiopia": "et",
  "Swaziland": "sz",
  "Uganda": "ug",
  "Egypt": "eg",
  "Zambia": "zm",
  "Togo": "tg",
  "India": "in",
  "Liberia": "lr",
  "Comoros": "km",
  "Madagascar": "mg",
  "Lesotho": "ls",
  "Burundi": "bi",
  "Zimbabwe": "zw",
  "Haiti": "ht",
  "Botswana": "bw",
  "Syria": "sy",
  "Malawi": "mw",
  "Yemen": "ye",
  "Rwanda": "rw",
  "Tanzania": "tz",
  "Afghanistan": "af",
  "Central African Republic": "cf",
  "South Sudan": "ss"
};

export default countryCodeMap;
